cmake_minimum_required(VERSION 3.10.0)
project(VS-Code-Projects VERSION 0.1.0 LANGUAGES C CXX)

add_executable(VS-Code-Projects "OOP Exercises/Exercise-1/main.cpp"
    "OOP Exercises/Exercise-2/exercise.cpp"
    "OOP Exercises/Exercise-3/exercise.cpp"
    "OOP Exercises/Exercise-4/exercise.cpp"
    "OOP Exercises/Exercise-5/exercise.cpp"
    "OOP Exercises/Exercise-6/exercise.cpp"
    "OOP Exercises/Exercise-7/exercise.cpp"
    "OOP Exercises/Exercise-8/exercise.cpp"
    "OOP Exercises/Exercise-9/exercise.cpp"
    "OOP Exercises/Exercise-10/exercise.cpp"
    "OOP Exercises/Exercise-11/exercise.cpp"
    "OOP Exercises/Exercise-12/exercise.cpp"
    structured-programming-exercises/Exercise-2/2.cpp
    structured-programming-exercises/Exercise-3/3.cpp
    structured-programming-exercises/Exercise-4/4.cpp
    structured-programming-exercises/Exercise-5/5.cpp
    structured-programming-exercises/Exercise-5/5-1.cpp
    structured-programming-exercises/Exercise-6/6.cpp
    structured-programming-exercises/Exercise-7/7.cpp
    structured-programming-exercises/Exercise-8/8.cpp
    structured-programming-exercises/Exercise-9/9.cpp
    structured-programming-exercises/Exercise-10/10.cpp
    structured-programming-exercises/Exercise-11/11.cpp
    structured-programming-exercises/Exercise-12/12.cpp)

