cmake_minimum_required(VERSION 3.10.0)
project(VS-Code-Projects VERSION 0.1.0 LANGUAGES C CXX)

add_executable(VS-Code-Projects Exercise-1/main.cpp Exercise-2/2.cpp Exercise-3/3.cpp
    Exercise-4/4.cpp
    Exercise-5/5.cpp
    Exercise-5/5-1.cpp
    Exercise-6/6.cpp
    Exercise-7/7.cpp
    Exercise-8/8.cpp
    Exercise-9/9.cpp
    Exercise-10/10.cpp
    Exercise-11/11.cpp
    Exercise-12/12.cpp)

